//  This file was generated by LevelHelper
//  http://www.levelhelper.org
//
//  LevelHelperLoader.h
//  Created by Bogdan Vladu
//  Copyright 2011 Bogdan Vladu. All rights reserved.
//
////////////////////////////////////////////////////////////////////////////////
//
//  This software is provided 'as-is', without any express or implied
//  warranty.  In no event will the authors be held liable for any damages
//  arising from the use of this software.
//  Permission is granted to anyone to use this software for any purpose,
//  including commercial applications, and to alter it and redistribute it
//  freely, subject to the following restrictions:
//  The origin of this software must not be misrepresented; you must not
//  claim that you wrote the original software. If you use this software
//  in a product, an acknowledgment in the product documentation would be
//  appreciated but is not required.
//  Altered source versions must be plainly marked as such, and must not be
//  misrepresented as being the original software.
//  This notice may not be removed or altered from any source distribution.
//  By "software" the author refers to this code file and not the application 
//  that was used to generate this file.
//
////////////////////////////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>
#import "cocos2d.h"
#include "Box2D.h"

@class LHLayer;
@class LHSprite;
@class LevelHelperLoader;

@interface LHBatch : CCSpriteBatchNode
{
    NSString* uniqueName;
    NSString* imagePath;
    NSString* shFile;
    __unsafe_unretained LevelHelperLoader* parentLoader;
}
@property (readonly) NSString* uniqueName;
@property (readonly) NSString* imagePath; 


+(id) batchWithDictionary:(NSDictionary*)dictionary layer:(LHLayer*)layer;
+(id) batchWithSheetName:(NSString*)sheetName shFile:(NSString*)spriteHelperFile;

-(void) removeSelf; //will also remove all the children

-(NSString*)shFile;

//if sprite is child of this batch node you can retrieve it
-(LHSprite*)spriteWithUniqueName:(NSString*)name;

-(NSArray*)allSprites;
-(NSArray*)spritesWithTag:(int)tag;
@end	
